using UnityEngine;
using System.Collections;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class TextoHistoriaInicial : MonoBehaviour {

	public Text campoTexto;
	public Text txtPular;
	public string[] texto;
	public float espera;
	public string sceneToLoad;

	// Use this for initialization
	void Start () {

		txtPular.canvasRenderer.SetAlpha (0.0f);
		texto = new string[] {
			"NOSSA AVENTURA COMEÇA EM UM MUNDO QUE ERA DIVIDIDO EM CINCO REINOS, QUE APÓS MUITOS ANOS DE GUERRAS, CAOS E MORTES, FIRMARAM UM ACORDO DE PAZ.",
			"OLDEOM, FICOU COMO O REINO RESPONSÁVEL PELA ADMINISTRAÇÃO GERAL DOS REINOS, ERA LIDERADO PELO REI MAGO GARMIT, OS OUTROS REINOS ERAM LIDERADOS PELOS REIS MAGOS (ALBERIC, AHTI, FATIN, MERLIN E VECTORIOUS).",
			"DE TEMPOS EM TEMPOS REUNIÕES ENTRE OS REIS ACONTECIAM PARA FORTALECER O ACORDO ENTRE OS REINOS E ACONTECIA EVENTOS DE PRÁTICA DE MÁGICA E NOVAS MÁGICAS DESCOBERTAS ERAM COMPARTILHADAS ENTRE TODOS.",
			"NO ENTANTO, UM DOS CINCO REIS MAGOS, ALBERIC, NÃO SEGUIA AS REGRAS ESTABELECIDAS NO ACORDO E PRATICAVA MÁGICAS COM BASE EM MAGIA NEGRA, PARA NÃO SER PERCEBIDO PELOS AMULETOS EM QUE OS MAGOS USAVAM PARA PROTEÇÃO E RASTREIO DE FEITIÇOS, POUCO A POUCO SUA AMBIÇÃO PELO PODER DE SE TORNAR O MAIS PODEROSO REI MAGO CRESCIA, COMO UMA CHAMA INDOMÁVEL.",
			"ATÉ QUE CERTO DIA, PRATICANDO E EXPERIMENTANDO O FEITIÇO QUE ACREDITAVA SER O QUE PODERIA SER O CAMINHO PARA A SUA SOBERANIA DE PODER, ALGO ESTRANHO ACONTECE E UMA EXPLOSÃO QUE FEZ ABRIR UM VÓRTICE DE ENERGIA QUE SE TORNOU UMA PASSAGEM ENTRE ESTE UNIVERSO E UM OUTRO, PORÉM DESCONHECIDO PARA ALBERIC.",
			"ESTE PORTAL DE REPENTE SOLTOU UMA NOVA EXPLOSÃO QUE AFETOU ALBERIC E TODOS OS REINOS, PORÉM AGORA, ALBERIC NÃO ERA MAS ELE MESMO, TORNOU-SE ALGUÉM DIFERENTE UMA INCORPORAÇÃO DE UM SER ONDE O OBJETIVO ERA TOMAR ESTA DIMENSÃO PARA ELE, ASSIM ALBERIC SERIA SUA MARIONETE PARA ISSO.",
			"ESTE SER FEZ COM QUE CRIATURAS MALIGNAS SAÍSSEM DO VÓRTICE E  SE DIRIGIU PARA OLDEOM PARA O INICIO DA EXECUÇÃO DE SEU PLANO.",
			"OS HABITANTES DE TODOS OS REINOS FORAM AFETADOS COM O PODER DO VÓRTICE, QUE OS TRANSFORMOU EM ORCS E ELFOS",
			"OS REINOS ENTÃO FORAM ATACADOS PELAS CRIATURAS QUE TOMARAM CADA REINO DE ACORDO COM UMA ESPÉCIE, O REINO DE OLDEOM FOI TOMADO PELOS DEMONIOS, O REINO DE SUDDENE EM ESQUELETOS VIVOS, SALISTICK EM LOBISOMENS, CALLISTIA EM VAMPIROS E DUNDEYA DRAGÕES.",
			"OS REIS MAGOS DOS REINOS NÃO FORAM AFETADOS JA QUE ESTAVAM COM O AMULETO DE PROTEÇÃO CONTRA MAGIA, PORÉM FORAM CAPTURADOS E PRESOS EM SEUS RESPECTIVOS REINOS.",
			"BRENT, ERA FILHO DE GARMIT, E ERA UM GAROTO QUE FOI TREINADO PARA SER UM GUERREIRO MAS QUE APRENDERA O BÁSICO DE MAGICA COM SEU PAI, NÃO FOI AFETADO PELO EFEITO DO VÓRTICE POIS TINHA UM AMULETO DE PROTEÇÃO QUE SEU PAI TINHA LHE POSTO POR PRECAUÇÃO.",
			"BRENT, ESTAVA EM SUDDENE TREINANDO SUA HABILIDADES DE COMBATE E LOGO FOI SURPRIENDIDO COM A INVASÃO DAS CRIATURAS E SEM SABER O QUE ESTÁ ACONTECENDO VAI EM BUSCA DE SABER OQ HOUVE E DESCOBRIR O PERIGO QUE O MUNDO ESTÁ CORRENDO."
		};
		//campoTexto.text = texto;
		StartCoroutine ("Soletrar",texto);
		StartCoroutine ("FadePular");
	}
	
	// Update is called once per frame
	void Update () 
	{
		if(Input.GetButtonDown("Submit"))
		{
			SceneManager.LoadScene (sceneToLoad);
		}
	}

	IEnumerator Soletrar(string[] texto)
	{
		for(int count = 0; count < texto.Length; count++)
		{
			int letras = 0;
			campoTexto.text = "";

			while(letras <= texto[count].Length -1)
			{
				campoTexto.text += texto[count][letras];
				letras++;
				yield return new WaitForSeconds (espera);
			}
			yield return new WaitForSeconds (3.0f);
		}
		yield return new WaitForSeconds (2.0f);
		SceneManager.LoadScene (sceneToLoad);

	}

	IEnumerator FadePular()
	{
		yield return new WaitForSeconds (2.0f);
		txtPular.CrossFadeAlpha (1.0f, 2.0f, false);
		yield return null;
	}
}
